#2026-06-14 17:45:52
#Sun Jun 14 17:45:52 CEST 2026
DB.Host=localhost
DB.Type=SQLite3
DB.name=C\:\\Winapp\\Banca\\Banca.db
DB.passwd=sicuelserver
DB.service=1433
DB.user=sqlgianni
FLAG_FILTRI=58
PERC_INDOV=40
QTA_THREADS=1
cardid.assoc.001=84806;cla
cardid.assoc.002=85928;eug
cardid.assoc.003=66542;eug
cardid.assoc.004=75883;cla
cdstt.avere=75
cdstt.col1=140
cdstt.col2=291
cdstt.dare=75
cdstt.heigt=1447
cdstt.lx=726
cdstt.ly=1085
cdstt.posX=-710
cdstt.posY=0
cdstt.saldo=75
cdstt.width=707
cdstt.x=-1104
cdstt.y=97
cercacdst.colCodStat2=80
cercacdst.colcodstat=80
cercacdst.coldescr=404
cercacdst.heigt=512
cercacdst.posX=-962
cercacdst.posY=438
cercacdst.width=616
check.convdb=true
descr.scrta.00.d=ACCREDITO STIPENDI ISTITUTO SICUREZZA SOC IALE PAGAMENTO PENSIONI APRILE 2023 Data Ordine\:26/04/2023 
descr.scrta.00.x=ACCREDITO STIPENDI ISTITUTO SICUREZZA SOC *IALE (PAGAMENTO PENSIONI) ([A-Z]+ [0-9]+) Data Ordine\:([0-9]{2}/[0-9]{2}/[0-9]{4})
descr.scrta.01.d=PAG.TO POS Del 26/05/23 Ore 09\:02 CANINI CARBURANTI SRL 
descr.scrta.01.x=PAG.TO (POS) Del [0-9]{2}/[0-9]{2}/[0-9]{2} Ore [0-9]{2}\:[0-9]{2} (.+)
descr.scrta.02.d=PAG.TO CARTAZZURRA Il 31/12/19 Ore 07\:46 MOSCIONI JOSEPHINE - P Nr.PAN\: 830000075883 
descr.scrta.02.x=PAG.TO (CARTAZZURRA) Il [0-9]{2}/[0-9]{2}/[0-9]{2} Ore [0-9]{2}\:[0-9]{2} (.+)
descr.scrta.03.d=PAG.TO POS Ora\: 16\:50 HOTEL DE FRANCE PONTOR SON Paese\: 029 FRANCIA 
descr.scrta.03.x=PAG.TO (POS) Ora\: [0-9]{2}\:[0-9]{2}(.+)
descr.scrta.04.d=PAG.POS CIRCUITO INTER Il 04/05/23 Ore 11\:22 A\: AGRIGARDEN S.R.L. VIA GUARDIA DEG 
descr.scrta.04.x=PAG.(POS) CIRCUITO (INTER) Il [0-9]{2}/[0-9]{2}/[0-9]{2} Ore [0-9]{2}\:[0-9]{2} A\:(.+)
descr.scrta.05.d=PAGAMENTO TRAMITE POS il 26/05/23 Ore 09\:02 CANINI CARBURANTI SRL 
descr.scrta.05.x=PAGAMENTO TRAMITE (POS) il [0-9]{2}/[0-9]{2}/[0-9]{2} Ore [0-9]{2}\:[0-9]{2} (.+)
excludedcols=idfile,id,movstr,valstr,descrcaus,costo,flag,idcodstat
filecodstats.date=2026-02-14 16\:59\:36
filecodstats.path=CodStat.properties
filter_files=estra,wise
frame.dimx=1147
frame.dimy=1271
frame.heigt=1447
frame.posX=-1287
frame.posY=0
frame.posx=-1151
frame.posy=83
frame.width=1294
gcdstview.colAssigned=57
gcdstview.colAvere=76
gcdstview.colCardid=67
gcdstview.colCodstat=78
gcdstview.colDare=72
gcdstview.colDescr=778
gcdstview.colDescrcds=194
gcdstview.colDtmov=119
gcdstview.colId=44
gcdstview.colTipo=81
gcdstview.lx=1624
gcdstview.ly=1069
gcdstview.x=-2078
gcdstview.y=220
last.dir=F\:\\Google Drive\\gennari\\Banche
logLevel=INFO
log_lev=48
log_mesg=1629
log_time=60
modcodstat.heigt=211
modcodstat.lx=430
modcodstat.ly=224
modcodstat.posX=-472
modcodstat.posY=527
modcodstat.width=444
modcodstat.x=-496
modcodstat.y=328
resview.lx=1591
resview.ly=1282
resview.x=-2312
resview.y=25
scartaDescr=false
skin.name=LoadBancaFX
sovrapp.lx=1987
sovrapp.ly=551
sovrapp.x=-2402
sovrapp.y=518
splitpos=0.5760
viewopts.lx=640
viewopts.ly=353
viewopts.x=-1767
viewopts.y=398
voci.scarta=contabile,liquido,margine,partitenonprenotate,partiteindisponibili,fidocc,partitedare,partiteavere
