#2026-07-03 17:27:13
#Fri Jul 03 17:27:13 CEST 2026
SQry_000=wise2024@@ListaMovimenti@2024@2024.04@.*wise.*@1@@
SQry_001=payp2024@@ListaMovimenti@2024@@payp@0@@
SQry_002=Tutti 2024@@ListaMovimenti@2024@@@0@@
SQry_003=contanti@@listaMovimentiContanti@@@@0@@
SQry_004=amazon@@ListaMovimenti@@@.*(AMZN)|(AMAZON)|(mktp).*@1@@
SQry_005=Codstat NULL@@listaMovimenti@2025@@@0@codstat is null@
