-- INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES 'XX','YY' )
-- srch: ^(0-9\\.+)=(.*)
-- repl: VALUES \('\1', '\2'\)


INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('01', 'Alimentare')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('01.01', 'Spese alimentari (titancoop, Baguette, etc..)')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('01.02', 'cene e ristoranti')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('01.03', 'asporto')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('01.04', 'bar e spizzichi')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('01.05', 'Mensa')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('01.06', 'Caffe')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('01.10', 'altri')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('02', 'Automezzi')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('02.01', 'Auto AUDI')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('02.01.01', 'Benzina e/o gasolio')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('02.01.02', 'Gomme')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('02.01.03', 'Revisione e/o bollo')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('02.01.04', 'tagliando')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('02.01.05', 'Accessori')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('02.02', 'Auto Vitara Eug')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('02.02.01', 'Benzina e/o gasolio')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('02.02.02', 'Gomme')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('02.02.03', 'Revisione e/o bollo')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('02.02.04', 'tagliando')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('02.03', 'Moto BMW GS 1250')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('02.04', 'Moto No. 2')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('02.05', 'Bici No. 1')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('02.06', 'Bici No. 2')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('02.07', 'Autostrada')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('02.07.08', 'Noleggio Auto')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('02.08', 'Noleggio Auto')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('03', 'Divertimenti')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('03.01', 'teatro')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('03.02', 'cinema')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('03.03', 'concerti')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('03.04', 'Musei')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('03.05', 'Libri')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('03.05.01', 'Acquisto Libri Amazon Kindle')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('03.05.02', 'Acquisto Libri Kobo')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('03.05.03', 'Abbonamenti a Giornali')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('03.06', 'Acquisto Corsi Internet')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('03.07', 'Abbonamento TV')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('03.08', 'Associazioni Culturali')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('04', 'Viaggi e Vacanze')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('04.01', 'Costo biglietti, treno, aereo')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('04.02', 'Hotel')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('04.03', 'Noleggio mezzi')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('04.03.01', 'Noleggio auto')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('04.03.02', 'Noleggio bici')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('04.03.03', 'Bus Turistici')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('04.03.04', 'Noleggio Sci')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('04.03.05', 'Ski Pass')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('04.04', 'Viaggi Organizzati')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('04.04.01', 'Viaggi Organizzati')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('05', 'Finanza e Banche')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('05.01', 'SMAC Card')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('05.02', 'Assegni vari')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('05.03', 'Rendite, Stipendi e pensioni')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('05.03.01', 'Stipendi')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('05.03.02', 'Pensione')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('05.03.03', 'Affitti percepiti')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('05.03.04', 'Eredita')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('05.04', 'Giroconto fra banche')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('05.05', 'Donazioni Varie')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('05.10', 'Banca CaRisp')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('05.10.01', 'Interessi bancario Carisp')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('05.10.02', 'Comissione Carisp')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('05.10.03', 'Costo manutenzione conto Carisp')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('05.10.04', 'Investimenti Carisp')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('05.10.05', 'Trasferimenti denaro Carisp')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('05.10.06', 'Prelev. Bancomat Carisp')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('05.20', 'Banca BSI')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('05.20.01', 'Interessi bancari BSI')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('05.20.02', 'Comissioni BSI')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('05.20.03', 'Costo manutenzione conto BSI')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('05.20.04', 'Investimenti BSI')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('05.20.05', 'Trasferimenti denaro BSI')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('05.20.06', 'Prelev. Bancomat BSI')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('05.30', 'BKN301 Cla')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('05.31', 'WISE Brussel')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('05.40', 'BKN301 Eug')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('05.50', 'Assicurazione Pancotti')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('05.60', 'Assicurazione Unipol')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('05.70', 'Assicurazione Zurich')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('05.80', 'Assicurazione Allianz')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('06', 'Famiglia')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('06.01', 'Alessandro')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('06.01.01', 'Riscatto Laurea')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('06.01.03', 'Regali Alessandro')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('06.02', 'Andrea')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('06.02.03', 'Lucia')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('06.02.04', 'Regali Andrea')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('06.03', 'Lucia')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('06.04', 'Regali')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('06.06', 'Nonna')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('10', 'E-commerce')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('10.01', 'Amazon')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('10.01.01', 'Accrediti/Addebiti da amazon')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('10.01.02', 'Spese su Amazon')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('10.02', 'Alibaba')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('20', 'Salute e Medicina')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('20.01', 'Spese in farmacia')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('20.02', 'Spese presso specialisti medici')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('20.02.01', 'Dentista')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('20.02.02', 'Fisio terapista')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('20.02.03', 'Ottico')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('20.02.04', 'Amplifon,Otorino')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('20.02.05', 'Ospedali')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('20.03', 'Wellfare')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('20.03.01', 'Barbiere')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('20.03.02', 'Parucchiere')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('20.03.03', 'Estetista')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('20.03.04', 'Sport e/o palestra')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('20.10', 'Abbigliamento')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('20.10.10', 'Abbigliamento uomo')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('20.10.20', 'Abbigliamento donna')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('20.10.30', 'Abbigliamento bambino')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('20.15', 'Regali vari')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('20.20', 'Spese scuola e/o scolastiche')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('30', 'Casa')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('30.01', 'spese manutenzione casa')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('30.01.01', 'Idraulico per la casa')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('30.01.02', 'Manutenzione Caldaia')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('30.01.03', 'Spese GE.CO o geco')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('30.01.04', 'Foto voltaico (OBSOLETO)')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('30.01.05', 'Elettricista per la casa')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('30.01.06', 'Imbianchino per la casa')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('30.01.07', 'Falegname per la casa')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('30.01.08', 'Architetto per la casa')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('30.01.10', 'Accessori X la casa')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('30.01.11', 'Televisione')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('30.01.12', 'Sanatoria')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('30.01.13', 'Avvocati X S. Michele')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('30.01.15', 'Giardinaggio')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('30.01.20', 'Rifacimenti della casa')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('30.01.99', 'Spese ausiliarie')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('30.02', 'Azienda dei Servizi')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('30.02.01', 'Luce')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('30.02.02', 'Acqua')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('30.02.03', 'Gas')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('30.03', 'Giardinaggio per la casa')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('30.04', 'telefono')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('30.05', 'foto voltaico')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('30.06', 'Uffici Stato')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('30.07', 'Internet')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('30.08', 'Software')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('30.50', 'Casa Dogana')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('30.50.01', 'Rendita casa dogana')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('30.50.02', 'spese casa dogana')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('30.50.10', 'Assic. Casa Dogana')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('30.51', 'Casa Nonna')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('30.51.10', 'Finanza')
INSERT INTO dbo.CodiciStat (codstat,descrstat) VALUES ('99', 'Spese Non Classificate')
