INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '01', 'Alimentare');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '01.01', 'Spese alimentari (titancoop, Baguette, etc..)');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '01.02', 'cene e ristoranti');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '01.03', 'asporto');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '01.04', 'bar e spizzichi');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '01.05', 'Mensa');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '01.06', 'Caffe');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '01.10', 'altri');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '02', 'Automezzi');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '02.01', 'Auto AUDI');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '02.01.01', 'Benzina e/o gasolio');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '02.01.03', 'Revisione e/o bollo');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '02.01.04', 'tagliando');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '02.01.05', 'Accessori');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '02.02', 'Auto Vitara Eug');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '02.02.01', 'Benzina e/o gasolio');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '02.02.03', 'Revisione e/o bollo');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '02.02.04', 'tagliando');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '02.03', 'Moto');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '02.07', 'Autostrada');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '02.08', 'Noleggio Auto');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '03', 'Divertimenti');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '03.01', 'teatro');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '03.02', 'cinema');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '03.03', 'concerti');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '03.04', 'Musei');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '03.05', 'Libri');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '03.05.01', 'Acquisto Libri Amazon Kindle');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '03.05.02', 'Acquisto Libri Kobo');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '03.05.03', 'Abbonamenti a Giornali');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '03.06', 'Corsi Internet');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '03.07', 'Abbonamento TV');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '03.08', 'Associazioni Culturali');

INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '04', 'Viaggi e Vacanze');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '04.01', 'Costo biglietti, treno, aereo');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '04.02', 'Hotel');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '04.03', 'Noleggio mezzi');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '04.03.01', 'Noleggio auto');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '04.03.02', 'Noleggio bici');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '04.03.03', 'Bus Turistici');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '04.03.04', 'Noleggio Sci');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '04.03.05', 'Ski Pass');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '04.04', 'Viaggi Organizzati');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '04.04.01', 'Viaggi Organizzati');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '05', 'Finanza e Banche');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '05.01', 'SMAC Card');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '05.02', 'Assegni vari');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '05.03', 'Rendite, Stipendi e pensioni');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '05.03.01', 'Stipendi');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '05.03.02', 'Pensione');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '05.03.03', 'Affitti percepiti');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '05.03.04', 'Eredita');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '05.04', 'Giroconto fra banche');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '05.05', 'Donazioni Varie');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '05.10', 'Banca CaRisp');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '05.10.01', 'Interessi bancario Carisp');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '05.10.02', 'Comissione Carisp');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '05.10.03', 'Costo manutenzione conto Carisp');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '05.10.04', 'Investimenti Carisp');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '05.10.05', 'Trasferimenti denaro Carisp');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '05.10.06', 'Prelev. Bancomat Carisp');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '05.20', 'Banca BSI');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '05.20.01', 'Interessi bancari BSI');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '05.20.02', 'Comissioni BSI');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '05.20.03', 'Costo manutenzione conto BSI');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '05.20.04', 'Investimenti BSI');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '05.20.05', 'Trasferimenti denaro BSI');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '05.20.06', 'Prelev. Bancomat BSI');

INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '05.30', 'BKN301');

INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '05.31', 'WISE Brussel');

INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '05.50', 'Assicurazione Pancotti');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '05.60', 'Assicurazione Unipol');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '05.70', 'Assicurazione Zurich');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '05.80', 'Assicurazione Allianz');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '06', 'Famiglia');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '06.01', 'Alessandro');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '06.01', 'Andrea');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '06.03', 'Lucia');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '10', 'E-commerce');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '10.01', 'Amazon');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '10.01.01', 'Accrediti/Addebiti da amazon');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '10.01.02', 'Spese su Amazon');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '10.02', 'Alibaba');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '20', 'Salute e Medicina');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '20.01', 'Spese in farmacia');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '20.02', 'Spese presso specialisti medici');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '20.02.01', 'Dentista');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '20.02.02', 'Fisio terapista');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '20.02.03', 'Ottico');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '20.02.05', 'Ospedali');

INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '20.03', 'Wellfare');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '20.03.01', 'Barbiere');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '20.03.02', 'Parucchiere');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '20.03.03', 'Estetista');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '20.03.04', 'Sport e/o palestra');

INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '20.10', 'Abbigliamento');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '20.10.10', 'Abbigliamento uomo');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '20.10.20', 'Abbigliamento donna');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '20.10.30', 'Abbigliamento bambino');

INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '20.15', 'Regali vari');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '20.20', 'Spese scuola e/o scolastiche');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '30', 'Casa');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '30.01', 'spese manutenzione casa');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '30.01.01', 'Idraulico per la casa');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '30.01.02', 'Manutenzione Caldaia');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '30.01.03', 'Spese GE.CO o geco');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '30.01.04', 'Foto voltaico');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '30.01.05', 'Elettricista per la casa');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '30.01.06', 'Imbianchino per la casa');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '30.01.07', 'Falegname per la casa');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '30.01.08', 'Architetto per la casa');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '30.01.10', 'Accessori X la casa');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '30.01.11', 'Televisione');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '30.01.12', 'Sanatoria');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '30.01.13', 'Avvocati X S. Michele');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '30.01.15', 'Giardinaggio');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '30.01.20', 'Rifacimenti della casa');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '30.01.99', 'Spese ausiliarie');

INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '30.02', 'Azienda dei Servizi');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '30.02.01', 'Luce');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '30.02.02', 'Acqua');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '30.02.03', 'Gas');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '30.03', 'Giardinaggio per la casa');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '30.04', 'telefono');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '30.06', 'Uffici Stato');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '30.07', 'Internet');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '30.08', 'Software');
INSERT INTO CodiciStat (codstat, descrstat) VALUES ( '99', 'Spese Non Classificate');

