(Nessun nome di colonna)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '01', 'Valore ammesso per accordo tra le parti', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '05', 'Prelev. Bancomat', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '06', 'Accredito per incassi con addebito in conto preautorizzato (Operazioni diverse da incassi RID)', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '07', 'Accredito per incassi con addebito in conto non preautorizzato o per cassa', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '08', 'Disposizioni di incasso preautorizzate impagate (Operazioni diverse da incassi RID)', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '09', 'Incasso tramite P.O.S.', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '10', 'Emissione assegni circolari o vaglia', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '11', 'Pagamento utenze (servizi pubblici, luce, gas, telefono, ecc.) (Da utilizzare per codici non riconducibili ai codici ZC, ZD e ZE)', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '13', 'Assegno', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '14', 'Acquisto Titoli BSI', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '15', 'Rimborso finanziamenti (mutui, prestiti personali, ecc.)', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '16', 'Comissioni su pagamenti', 1)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '17', 'Assicurazione Bancaria', 1)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '18', 'Interessi Bancari', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '19', 'Ritenute', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '20', 'Canone cassette di sicurezza e custodia valori', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '21', 'Contributi assistenziali e previdenziali', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '22', 'Diritti custodia Titoli', 1)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '24', 'Pagamento o incasso di documenti sull’Italia', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '26', 'Bonifico', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '27', 'Stipendio/pensione', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '28', 'Acquisto e vendita divise e/o banconote estere (Per operazioni diverse da compravendita banconote estere, la causale e’ da utilizzare solo nei casi in cui la motivazione del pagamento non possa essere ricondotta agli altri codici elencati)', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '29', 'Accrediti RI.BA.', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '30', 'Accrediti effetti s.b.f.', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '31', 'Effetti ritirati (pagati)', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '32', 'Effetti richiamati', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '34', 'Estinzioni conto previd.', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '35', 'Storni RI.BA.', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '37', 'Insoluti RI.BA.', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '39', 'Vostra disposizione per emolumenti (stipendi, pensioni ecc.)', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '41', 'Pagamento o disposizione a mezzo sportello automatico', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '42', 'Effetti insoluti o protestati', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '43', 'Pagamento POS', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '44', 'Addebito per utilizzo di credito documentario su estero', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '45', 'Pagamento Carta Credito', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '46', 'Mandati di pagamento', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '47', 'Accredito per utilizzo credito documentario sull’Italia', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '48', 'Versamento con Bonifico', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '49', 'Valore ammesso per accordo tra le parti', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '5', 'Prelev. Bancomat', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '50', 'RID Rapporto Interbancario Diretto', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '51', 'Assegni turistici', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '52', 'Prelevamento con moduli di sportello ', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '53', 'Addebito per utilizzo di credito documentario sull’Italia', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '55', 'Assegni bancari insoluti o protestati', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '56', 'Ricavo effetti o assegni in lire e/o valuta estera al dopo incasso (sull’Italia)', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '57', 'Restituzione di assegni o vaglia irregolari', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '58', 'Reversali d¿incasso', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '60', 'Rettifica valuta', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '62', 'Saldo', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '63', 'Accrediti sconto effetti diretti', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '64', 'Accrediti effetti presentati allo sconto (sull’Italia)', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '65', 'Competenze di sconto', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '66', 'Canoni vari', 1)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '68', 'Storni vari', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '70', 'Acquisto/vendita a pronti titoli e diritti di opzione', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '72', 'Accredito per utilizzo di credito documentario da estero', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '74', 'Valori bollati', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '78', 'Versamento di contante o valori assimilati', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '79', 'Disposizione di giro conto (da/a altra banca) ', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '80', 'Acquisto/Vendita a termine titoli', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '81', 'Accensione riporto titoli', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '82', 'Estinzione riporto titoli', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '83', 'Iscriz. Fondi', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '84', 'Rimborso Titoli', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '85', 'Aumento di capitale o operazioni societarie', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '86', 'Finanziamenti import', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '87', 'Anticipazioni export', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '88', 'Valore ammesso per accordo tra le parti', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '90', 'Pagamento o incasso di rimesse documentate da o per l’estero ', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '91', 'Prelevamento a mezzo sportello automatico di altra banca', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '92', 'Costo libretto assegni', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '93', 'Valore ammesso per accordo tra le parti', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '94', 'Commissioni e spese su operazioni in titoli', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '95', 'Commissioni e spese su operazioni con l’estero ', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '96', 'Rettifica importo', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( '99', 'Accredito per rimborsi imposte ‘conto fiscale’', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( 'CO', 'Contante', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( 'PP', 'PayPal', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( 'S1', 'SMAC - Pagamento con SMAC', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( 'S2', 'SMAC - Pagamento con SMAC con Ricarica', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( 'S3', 'SMAC - SMAC Fiscale', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( 'S4', 'SMAC - Ricarica su SMAC', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( 'S5', 'SMAC - Accredito su SMAC', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( 'S6', 'SMAC - Manca la decodificata ', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( 'Y1', 'Anticipazioni su fatture Italia', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( 'Z1', 'Disposizioni di giro di cash pooling', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( 'Z2', 'Versamento di assegni bancari, assegni di conto corrente postale', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( 'Z3', 'Versamento di assegni circolari emessi da altre banche', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( 'Z4', 'Versamento di assegni postali non standardizzati', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( 'Z5', 'Versamento indiretto. Versamento di contante e/o assegni eseguito da soggetto diverso dal titolare del conto', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( 'Z6', 'Prelevamento eseguito da soggetto diverso dal titolare del conto', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( 'Z7', 'Accredito RID', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( 'Z8', 'Accredito MAV', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( 'Z9', 'Insoluto/storno RID', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( 'ZA', 'Insoluto MAV', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( 'ZB', 'Incasso certificati conformita�', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( 'ZC', 'Pagamento per fornitura elettrica', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( 'ZD', 'Pagamento per servizio telefonico', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( 'ZE', 'Pagamento per servizi acqua/gas', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( 'ZF', 'Pagamento per operazioni su prodotti derivati', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( 'ZG', 'Accredito per operazioni su prodotti derivati', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( 'ZH', 'Rimborso titoli e/o fondi comuni', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( 'ZI', 'Bonifico dall�estero', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( 'ZL', 'Bonifico sull�estero', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( 'ZM', 'Sconto effetti sull�estero', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( 'ZN', 'Negoziazione assegni sull�estero', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( 'ZP', 'Commissioni e spese su fideiussioni (Da utilizzare per operazioni estero e Italia)', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( 'ZQ', 'Commissioni e spese su crediti documentari', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( 'ZR', 'Penali', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( 'ZS', 'Erogazione prestiti personali e finanziamenti diversi', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( 'ZT', 'Pagamento/incasso bollettino bancario', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( 'ZU', 'Bonifico per previdenza complementare', 0)
INSERT INTO causali (abicaus, descrcaus, costo) VALUES ( 'ZX', 'Bonifico oggetto di oneri deducibili o detrazioni di imposta', 0)
